site_name: Atelier
site_description: Wed Documentation for the Atelier SDK
site_url: https://iteralabs.github.io/atelier-webdocs
repo_url: https://github.com/iteralabs/atelier
repo_name: atelier
site_author: Iteralabs.ai
docs_dir: docs

theme: 
  name: terminal
  language: en
  palette: Sans
  features:
    - revision.date
    - revision.history

nav: 
  - Home: 'index.md'

  - Overview: 'overview/overview.md'

  - Getting Started: 
    - Installation: 'getting_started/installation.md'

  - Logs:
    - Logging : 'logs/logs.md'

  - Implementation:
    - Usage Patterns: 'implementation/usage_patterns.md'
    - Platform Specifications: 'implementation/platform_specs.md'
  
  - Support:
    - Common Issues: 'support/common_issues.md'
    - FAQ: 'support/faq.md'
    - Release Notes: 'support/release_notes.md'

  - Contact:
    - Get in Touch: 'contact/get_in_touch.md' 
plugins:
  - search
    
extra_css:
  - assets/style.css

copyright: Copyright &copy; 2025 iteralabs.ai

