site_name: Atelier
theme: 
  name: terminal
  language: en

nav: 
  - Home: 'index.md'

  - Overview: 'overview.md'

  - Getting Started: 
    - Installation: 'installation.md'

  - Logs:
    - Logging : 'Logging.md'

  - Implementation:
    - Usage Patterns: 'design_patterns.md'
    - Platform Specifications: 'platform_specs.md'
    - Other libraries: 'other_libraries.md'
  
  - Support:
    - Common Issues: 'common_issues.md'
    - FAQ: 'faq.md'
    - Release Notes: 'release_notes.md'

  - Contact:
    - Get in Touch: 'get_in_touch.md' 
